# Generated by Django 3.2.4 on 2021-06-28 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('JavaScript', 'Javascript'), ('Python', 'Python'), ('UI/UX', 'Ui Ux'), ('Random', 'Random')], default='Random', max_length=55)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=9)),
                ('day', models.CharField(max_length=2)),
                ('year', models.CharField(default='2021', max_length=4)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
