# Generated by Django 3.2.4 on 2021-06-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('JavaScript', 'Javascript'), ('Python', 'Python'), ('UI/UX', 'Ui Ux'), ('Random', 'Random')], default='Random', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='year',
            field=models.CharField(default='2021', max_length=4),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='month',
            field=models.CharField(max_length=9),
        ),
    ]
