# Generated by Django 3.2.4 on 2021-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('JavaScript', 'Javascript'), ('Python', 'Python'), ('Design', 'Design'), ('Random', 'Random')], default='Random', max_length=55),
        ),
    ]
