# Generated by Django 3.2.4 on 2021-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
