# Generated by Django 3.2.4 on 2021-06-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('JavaScript', 'Javascript'), ('Python', 'Python'), ('UI/UX', 'Ui Ux'), ('Random', 'Random')], default='Random', max_length=101),
        ),
    ]
