# Generated by Django 3.2.4 on 2021-06-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('JavaScript', 'Javascript'), ('Python', 'Python'), ('UI/UX', 'Ui Ux'), ('Random', 'Random')], default='Random', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
