# Generated by Django 3.2.4 on 2021-06-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20210628_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('JavaScript', 'Javascript'), ('Python', 'Python'), ('UI/UX', 'Ui Ux'), ('Random', 'Random')], default='Random', max_length=55),
        ),
    ]
